export const lines = [
  '$ whoami',
  '',
  '>> We are ByteBandits — digital specialists & system rebels.',
  '',
  'We build one-off tools, event apps, and rapid MVPs.',
  'No overhead. No lock-ins. Just clean code that does the job.',
  '',
  'We believe in:',
  '  🔁 Fast feedback loops',
  '  ⚡ Getting it working, not endlessly planning',
  '  🤝 Honest engineering over sales fluff',
  '',
  'No fluff. No shortcuts. Just solid engineering.',
];
