// src/pages/Contact.jsx
export const lines = [
  '$ nc bytebandits.io 31337',
  '',
  '[link] Negotiating TLS tunnel ...... OK',
  '',
  'Need a prototype, pitch build, or rogue automation?',
  'Drop the payload, we drop the code. No lock-ins. No ghosting.',
  '',
  'contact vector:',
  '  max [at] byte [minus] bandits [dot] com',
  '  subject: MISSION // <your codename>',
  '',
  'Telemetry we love:',
  '  ▸ problem in one sentence',
  '  ▸ deadline window',
  '  ▸ stack constraints (if any)',
  '',
  'We respond in <24h unless we are mid-run.',
];
