export const lines = [
  '$ echo "Welcome to ByteBandits OÜ"',
  '>> Boot sequence initialized...',
  '>> Establishing encrypted uplink...',
  '>> Compiling code... ███████████] 100%',
  '',
  'We are digital outlaws — crafting custom software with precision.',
  'Special ops in:',
  '   • Web Apps',
  '   • Mobile Apps',
  '',
  '💡 Need something fast and custom-built?',
  '🚀 ByteBandits delivers working prototypes in days — not quarters.',
  '🎯 One mission at a time. One client at a time.',
  '',
];
