export const lines = [
  '    ____        __       __                    ___ __      ',
  '   / __ )__  __/ /____  / /_  ____ _____  ____/ (_) /______',
  '  / __  / / / / __/ _ \\/ __ \\/ __ `/ __ \\/ __  / / __/ ___/',
  ' / /_/ / /_/ / /_/  __/ /_/ / /_/ / / / / /_/ / / /_(__  ) ',
  '/_____\\/\\__, /\\__/\\___/_.___/\\__,_/_/ /_/\\__,_/_/\\__/____/  ',
  '      /____/                                               ',
  '',
  '$ echo "Welcome to ByteBandits OÜ"',
  '>> Boot sequence initialized...',
  '>> Establishing encrypted uplink...',
  '>> Compiling code... ███████████] 100%',
  '',
  'We are digital outlaws — crafting custom software with precision.',
  'Special ops in:',
  '   • Web Apps',
  '   • Mobile Apps',
  '',
  '💡 Need something fast and custom-built?',
  '🚀 ByteBandits delivers working prototypes in days — not quarters.',
  '🎯 One mission at a time. One client at a time.',
  '',
];
