export const lines = [
  '┌───────────────────────────────────────────────┐',
  '│ BYTEBANDITS OÜ // NODE: TALINN/BB-NEXUS       │',
  '└───────────────────────────────────────────────┘',
  '$ bootctl --status',
  '[00:00:01] INIT......OK',
  '[00:00:03] LINK......Encrypted uplink established',
  '[00:00:05] CORE......Compiling mission payload ███████████] 100%',
  '',
  '$ cat manifesto.txt',
  'We are digital outlaws wiring bespoke software with surgical focus.',
  'Only one mission per squad. No dead weight. No backlog theater.',
  '',
  'payload.modules:',
  '  ▸ Web Ops    :: dashboards, control rooms, internal tooling',
  '  ▸ Mobile Ops :: Flutter/React Native strike teams',
  '  ▸ Rapid MVPs :: proof-of-life builds in days, not quarters',
  '',
  'signal>',
  '  "Need something fast? We ghost-in, deliver, and vanish."',
  '',
  ':: Type a section name or hit the menu to move around ::'
];
