export const lines = [
  '$ tail -f services.log',
  '────────────────────────────────────────────────────────',
  '[SERVICES::SCAN]',
  '',
  '▸ MOBILE/EDGE CLIENTS',
  '   Stack: Flutter · React Native · Capacitor',
  '   Use: event tools, companion apps, device dashboards',
  '',
  '▸ WEB CONSOLES & OPS PANELS',
  '   Stack: React · Vite · Firebase/Supabase',
  '   Use: internal tooling, analytics, live control rooms',
  '',
  '▸ RAPID MVP SPRINTS',
  '   Deliverable: clickable proof-of-life in ≤ 7 days',
  '   Extras: branding shots, launch copy, landing pages',
  '',
  '▸ ONE-OFF UTILITIES',
  '   Small automations, kiosks, pop-up experiences, art drops',
  '',
  ':: SLA :: We prototype under blackout conditions, keep comms async,',
  ':: and ship the binary plus docs so your crew can extend it later.'
];
