export const lines = [
  '$ cat services.txt',
  '',
  '>> Our Services:',
  '',
  '📱 Mobile & Desktop Apps',
  '   - Flutter, React Native',
  '',
  '🎨 UX/UI Design & Branding',
  '   - Minimal. Functional. On point.',
  '',
  '🧪 MVPs & One-Off Builds',
  '   - Need a tool for just one day or demo? We’ve got you.',
  '',
  '⚡ Rapid Prototyping',
  '   - We build in hours or days, not months.',
];
